stages:
  - deploy

before_script:
  - apk add rsync openssh
  - echo "$CI_ENV_FILE" > .env

deploy:
  image: alpine
  stage: deploy
  only:
    - tags
  cache:
    paths:
      - .cache
  script:
    - mkdir -p ~/.ssh
    - echo "$CI_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -av --exclude='.git/' --progress --delete ./ $CI_REMOTE_USERNAME@$CI_REMOTE_HOST:$CI_REMOTE_PATH
    - ssh $CI_REMOTE_USERNAME@$CI_REMOTE_HOST "cd $CI_REMOTE_PATH && sudo docker compose up -d --build"
